version: '3.8'

services:
  bot.api:
    container_name: botapi
    build:
      context: .
      dockerfile: Bot.Api/Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "8443:8443"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=E-CommerceBotDb;User Id=postgres;Password=12345
      - ConnectionStrings__Redis=redis:6379
      - BotConfiguration__BotToken=6938864415:AAFOoRGsyop4EztK2e5zS4bcDflR78Ze_rI
      - BotConfiguration__HostAddress=https://cacc-82-215-114-176.ngrok-free.app
      - BotConfiguration__SecretKey=qwertyuiop
      - BotConfiguration__Route=/api/bot
    networks:
      - ecommerce

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ecommerce

  db:
    image: postgres:16
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_DB: E-CommerceBotDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - ecommerce

volumes:
  data:
  redis-data:
networks:
  ecommerce:
    driver: bridge  
